### ISSUE TITLE
Add code of conduct template

### ISSUE THREAD

**Issue by adarshaacharya** [adarshaacharya/ApiHub#1]
- add template for `CODE_OF_CONDUCT.md`
ref : https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by MagicMarcos** [comment]
I'd be happy to do this for you, my friend.

**Comment by MagicMarcos** [comment]
Submitted a pull request with code of conduct file

**Comment by adarshaacharya** [comment]
Thanks will merge this PR. :)
